### PR TITLE
Fix Extraneous Array Schemas

### LINKED ISSUE #195: Extraneous Schemas Generated for Models Containing Array Properties
This might be related to #63

Note: We use this package directly, not as part of [swagger-akka-http](https://github.com/swagger-akka-http/swagger-akka-http). We only generate schemas for models, and don't use any annotations.

Given a case class that contains a single property which is a `Seq`, there are two schemas generated, `Foo` and `SeqString`, i'm unsure why the `SeqString` schema is generated as it's not referenced in the `Foo` schema. This appears to be a bug.

```scala
    case class Foo(bar: Seq[String])
    val schema = ModelConverters.getInstance().readAll(classOf[Foo])
    val yaml = Yaml.pretty(schema)
    println(yaml)
```

```yaml
Foo:
  required:
    - bar
  type: object
  properties:
    bar:
      type: array
      items:
        type: string
SeqString:
  type: array
  items:
    type: string
```

### PR DESCRIPTION
**Pull request by leedsalex**
fixes https://github.com/swagger-akka-http/swagger-scala-module/issues/195

I think I figured out the issue in the referenced ticket, at least, this fix works for me in a spec with over 500 schemas and paths... 

Apologies in advance for a terrible explanation:

From my understanding in the final case where the resolver eventually calls the next converter on the chain, which I believe to be the default converter in `swagger-core`, we are provided with a schema not processed by this library. In the specific case that this schema is for an iterable type property, the converter comes up with some nonsense name for the schema, i.e. `SeqString` which results in it being treated as a root level schema. By removing the name, this schema somehow gets removed from the output.

### CODE REVIEW

**Comment by pjfanning** [comment]
this does improve the scenario you mentioned in #195 but it breaks another test case.

val schemas = converter.readAll(classOf[Seq[String]]).asScala.toMap -- this test now returns an empty map and in this case, I think it should still contain an entry.

I'm not sure how to proceed right now but I'd prefer not to break this other test.

**Comment by leedsalex** [comment]
@pjfanning 
Glad you have a great test suite! 
I added a condition to determine if a parent exists. What do you think of this approach?

File: src/test/scala/com/github/swagger/scala/converter/ScalaModelTest.scala [hunk 1]
```diff
@@ -75,13 +75,17 @@ class ScalaModelTest extends AnyFlatSpec with Matchers {
 
   it should "read a model with vector property" in {
     val schemas = ModelConverters.getInstance().readAll(classOf[ModelWithVector]).asScala
+    schemas.size shouldBe 1
```
Comment (pjfanning) [inline src/test/scala/com/github/swagger/scala/converter/ScalaModelTest.scala:78]: minor: `schemas should have size 1` -- when this assertion fails the error message includes the toString of schemas -- I'll fix that

**Comment by leedsalex** [comment]
Thank you for merging this in! I would really appreciate it if you could publish this into a new version when you get the chance. Thanks again!

**Comment by pjfanning** [comment]
Could you use a snapshot build? They are published after every merge.

The next planned release will be in about 3 weeks time when Jackson 2.14.0 is officially released.
